config/routes.rb
Rails.application.routes.draw do

  resources :songs, only: [:index, :show]
  resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  validates_presence_of :name
  validates_uniqueness_of :name, with: :message

  def average_song_length
    songs.average(:length)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :find_artist, only: [:show, :destroy, :edit, :update]

  def index
    @artists = Artist.all
  end
  
  def show
  end

  def new
  end

  def create
    Artist.create!(artist_params)
    redirect_to artists_path
  end

  def destroy
    @artist.destroy 
    redirect_to artists_path
  end

  def edit
  end

  def update
    @artist.update(artist_params)
    flash.notice = "#{@artist.name} Updated!"
    redirect_to artists_path
  end

  private
  def find_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<h1 style="color:SlateBlue;">Update <%= @artist.name %></h1>

<%= form_with url: artist_path(@artist), method: :patch, local: true do |f| %>

  <%= f.label :name, 'Name:' %><br>
  <%= f.text_field :name %><br/>

  <%= f.submit 'Update Artist' %>
<% end %>

app/views/artists/index.html.erb
<h1 style="color:SlateBlue;">Isabelles Artists</h1>

<% @artists.each do |a| %>
  <h2 style="color:Violet;"><%= a.name %>
  <%= button_to 'Delete', artist_path(a), method: :delete %>
  <%= button_to 'Edit', edit_artist_path(a), method: :get %></h2>
<% end %>

<%= link_to "Create New Artist", new_artist_path, style: "color: #F4ADC6;" %>

app/views/artists/new.html.erb
<h1 style="color:SlateBlue;">Enter Artist Info</h1>

<%= form_with model: @artist, url: artists_path, method: :post, class: 'artists_form', local: true do |f| %>

  <%= f.label :name, 'Name:' %><br>
  <%= f.text_field :name %><br/>

  <%= f.submit 'Create Artist' %>
<% end %>

app/views/artists/show.html.erb
<h1 style="color:Violet;"><%= @artist.name %> Info</h1>
<p style="color:SlateBlue;"><b>Average Length of Songs: </b><%= @artist.average_song_length %></p>
<p style="color:SlateBlue;"><b>Count of Songs: </b><%= @artist.songs.count %></p>

<%= link_to "Take Me Back", artists_path, style: "color: #F4ADC6;" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IsabelleSetList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1 style="color:SlateBlue;">Isabelles Song List</h1>

<% @songs.each do |song| %>
  <h2 style="color:Violet;"><b>Title: </b><%= song.title %></h2>
  <p style="color:MediumSeaGreen;"><b>Play Count: </b><%= song.play_count %></p>
<% end %>

app/views/songs/show.html.erb
<h1 style="color:SlateBlue;"><%= @song.title %> Song Info</h1>
<h3 style="color:Violet;">By: <%= @song.artist.name %></h3>
<p style="color:MediumSeaGreen;"><b>Length: </b><%= @song.length %></p>
<p style="color:MediumSeaGreen;"><b>Play Count: </b><%= @song.play_count %></p><br/>

<%= link_to "Take Me Back", songs_path, style: "color: #F4ADC6;" %>